/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import { HTMLStencilElement, JSXBase } from '@stencil/core/internal';


export namespace Components {
  interface NtaraModal {
    'closeOutside': boolean;
    'cornerRadius': string;
    'lightbox': string;
    'margin': string;
    'show': boolean;
    'showClose': boolean;
    'zIndex': string;
  }
  interface NtaraSticky {
    /**
    * Defines the vertical position of the element relative to it's parent container.
    */
    'offset': number;
    /**
    * Sets the element's parent container. Assists in calculating offsets for multiple instances of <ntara-sticky>.
    */
    'parent': HTMLElement;
    /**
    * Detects the current browser's support for position: sticky. - Defaults to false if IE11 user agent is detected. - If unsupported, instantiates stickybits polyfill.
    */
    'stickySupported': boolean;
    /**
    * Sets the z-index value of the sticky element.
    */
    'zIndex': number;
  }
}

declare global {


  interface HTMLNtaraModalElement extends Components.NtaraModal, HTMLStencilElement {}
  var HTMLNtaraModalElement: {
    prototype: HTMLNtaraModalElement;
    new (): HTMLNtaraModalElement;
  };

  interface HTMLNtaraStickyElement extends Components.NtaraSticky, HTMLStencilElement {}
  var HTMLNtaraStickyElement: {
    prototype: HTMLNtaraStickyElement;
    new (): HTMLNtaraStickyElement;
  };
  interface HTMLElementTagNameMap {
    'ntara-modal': HTMLNtaraModalElement;
    'ntara-sticky': HTMLNtaraStickyElement;
  }
}

declare namespace LocalJSX {
  interface NtaraModal {
    'closeOutside'?: boolean;
    'cornerRadius'?: string;
    'lightbox'?: string;
    'margin'?: string;
    'onClose-clicked'?: (event: CustomEvent<any>) => void;
    'onModal-closed'?: (event: CustomEvent<any>) => void;
    'onModal-opened'?: (event: CustomEvent<any>) => void;
    'show'?: boolean;
    'showClose'?: boolean;
    'zIndex'?: string;
  }
  interface NtaraSticky {
    /**
    * Defines the vertical position of the element relative to it's parent container.
    */
    'offset'?: number;
    /**
    * Sets the element's parent container. Assists in calculating offsets for multiple instances of <ntara-sticky>.
    */
    'parent'?: HTMLElement;
    /**
    * Detects the current browser's support for position: sticky. - Defaults to false if IE11 user agent is detected. - If unsupported, instantiates stickybits polyfill.
    */
    'stickySupported'?: boolean;
    /**
    * Sets the z-index value of the sticky element.
    */
    'zIndex'?: number;
  }

  interface IntrinsicElements {
    'ntara-modal': NtaraModal;
    'ntara-sticky': NtaraSticky;
  }
}

export { LocalJSX as JSX };


declare module "@stencil/core" {
  export namespace JSX {
    interface IntrinsicElements {
      'ntara-modal': LocalJSX.NtaraModal & JSXBase.HTMLAttributes<HTMLNtaraModalElement>;
      'ntara-sticky': LocalJSX.NtaraSticky & JSXBase.HTMLAttributes<HTMLNtaraStickyElement>;
    }
  }
}


