/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import { HTMLStencilElement, JSXBase } from '@stencil/core/internal';


export namespace Components {
  interface NtaraSticky {
    'defaultPosition': string;
    'fixedWidth': string;
    'offset': number;
    'parent': HTMLElement;
    'userAgent': string;
    'zIndex': number;
  }
}

declare global {


  interface HTMLNtaraStickyElement extends Components.NtaraSticky, HTMLStencilElement {}
  var HTMLNtaraStickyElement: {
    prototype: HTMLNtaraStickyElement;
    new (): HTMLNtaraStickyElement;
  };
  interface HTMLElementTagNameMap {
    'ntara-sticky': HTMLNtaraStickyElement;
  }
}

declare namespace LocalJSX {
  interface NtaraSticky extends JSXBase.HTMLAttributes<HTMLNtaraStickyElement> {
    'defaultPosition'?: string;
    'fixedWidth'?: string;
    'offset'?: number;
    'parent'?: HTMLElement;
    'userAgent'?: string;
    'zIndex'?: number;
  }

  interface IntrinsicElements {
    'ntara-sticky': NtaraSticky;
  }
}

export { LocalJSX as JSX };


declare module "@stencil/core" {
  export namespace JSX {
    interface IntrinsicElements extends LocalJSX.IntrinsicElements {}
  }
}


